version: '3'

services:
  nginx:
    build:
      context: nginx
    image: esdrasvitor/fullcycle2-docker-desafio2-nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    tty: true
  
  app: 
    build:
      context: node
    image: esdrasvitor/fullcycle2-docker-desafio2-node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 360s docker-entrypoint.sh node index.js
    networks:
      - node-network
    tty: true

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge